"""
ml/shared/config.py

Prediction window configuration per symbol.
"""

import yaml
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Optional

CONFIG_PATH = Path(__file__).resolve().parent.parent / "config" / "prediction_windows.yaml"


@dataclass
class SymbolConfig:
    """Configuration for a single symbol's prediction window."""
    window_minutes: int
    confidence_threshold: float
    fallback_window: Optional[int]
    entry_quality_improvement: float
    calibrated: str


@dataclass
class PredictionWindowConfig:
    """Full prediction window configuration."""
    default_window: int
    default_threshold: float
    symbols: dict[str, SymbolConfig]

    def get(self, symbol: str) -> SymbolConfig:
        """Get config for a symbol, falling back to defaults."""
        symbol = symbol.upper()
        if symbol in self.symbols:
            return self.symbols[symbol]
        return SymbolConfig(
            window_minutes=self.default_window,
            confidence_threshold=self.default_threshold,
            fallback_window=None,
            entry_quality_improvement=0.0,
            calibrated="default",
        )


def load_prediction_config() -> PredictionWindowConfig:
    """Load prediction window config from YAML file."""
    if not CONFIG_PATH.exists():
        # Return defaults if config file doesn't exist
        return PredictionWindowConfig(
            default_window=60,
            default_threshold=0.65,
            symbols={},
        )

    with open(CONFIG_PATH) as f:
        raw = yaml.safe_load(f)

    defaults = raw.get("defaults", {})
    default_window = defaults.get("window_minutes", 60)
    default_threshold = defaults.get("confidence_threshold", 0.65)

    symbols = {}
    for sym, cfg in raw.get("symbols", {}).items():
        symbols[sym.upper()] = SymbolConfig(
            window_minutes=cfg.get("window_minutes", default_window),
            confidence_threshold=cfg.get("confidence_threshold", default_threshold),
            fallback_window=cfg.get("fallback_window"),
            entry_quality_improvement=cfg.get("entry_quality_improvement", 0.0),
            calibrated=str(cfg.get("calibrated", "unknown")),
        )

    return PredictionWindowConfig(
        default_window=default_window,
        default_threshold=default_threshold,
        symbols=symbols,
    )


def save_prediction_config(config: PredictionWindowConfig) -> None:
    """Save prediction window config to YAML file."""
    data = {
        "defaults": {
            "window_minutes": config.default_window,
            "confidence_threshold": config.default_threshold,
        },
        "symbols": {},
    }

    for sym, cfg in sorted(config.symbols.items()):
        data["symbols"][sym] = {
            "window_minutes": cfg.window_minutes,
            "confidence_threshold": cfg.confidence_threshold,
            "fallback_window": cfg.fallback_window,
            "entry_quality_improvement": cfg.entry_quality_improvement,
            "calibrated": cfg.calibrated,
        }

    # Add header comment
    header = """# Prediction window configuration per symbol
# Generated by: ml/models/session_direction/explore_confidence.py
# Last calibrated: {date}
# Recalibrate quarterly or after significant regime changes

""".format(date=date.today().isoformat())

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_PATH, "w") as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)


def update_symbol_config(
    symbol: str,
    window_minutes: int,
    confidence_threshold: float,
    fallback_window: Optional[int],
    entry_quality_improvement: float,
) -> None:
    """Update config for a single symbol, preserving others."""
    config = load_prediction_config()

    config.symbols[symbol.upper()] = SymbolConfig(
        window_minutes=window_minutes,
        confidence_threshold=confidence_threshold,
        fallback_window=fallback_window,
        entry_quality_improvement=entry_quality_improvement,
        calibrated=date.today().isoformat(),
    )

    save_prediction_config(config)
